In [ ]:
import sys
import os
import time

In [ ]:
# include path to our library
cwd = os.getcwd()
dir_path = os.path.dirname(os.path.realpath(cwd))
sys.path.append(dir_path)
time.sleep(2)

In [ ]:
dir_path
%cd $dir_path
!ls

In [ ]:
import argparse
import json

from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import set_random_seed

import keras.backend as K
from keras.backend.tensorflow_backend import set_session

from core.data.data_loader import *
from core.models.lstm import ModelLSTM, ModelLSTMParalel, ModelLSTMCuDnnParalel
from core.models.cnn import ModelCNN
from core.models.mlp import ModelMLP

from core.utils.metrics import *
from core.utils.utils import *


## loading Configurartion ##


In [ ]:
# load some configurations configurations of model and others
configs = json.load(open('config_lstm.json', 'r'))
output_path = configs['paths']['save_dir']
output_logs = configs['paths']['log_dir']

if os.path.isdir(output_path) == False:
    os.mkdir(output_path)

if os.path.isdir(output_logs) == False:
    os.mkdir(output_logs)        

time_steps =  configs['model']['layers'][0]['input_timesteps']  # the number of points or hits
num_features = configs['model']['layers'][0]['input_features']  # the number of features of each hits
split_data = configs['data']['train_split']  # the number of features of each hits
cylindrical = configs['data']['cylindrical']  # set to polar or cartesian coordenates
#cylindrical = False
normalise = configs['data']['normalise'] 
num_hits = configs['data']['num_hits']

print('OK reading of json file')


## Setup Data ##

In [ ]:
# reading path of data
path = configs['data']['filename']
path

In [ ]:
data = Dataset(path, split_data, cylindrical, num_hits, KindNormalization.Zscore)
# divimos 


In [ ]:
data.data_train.iloc[0:12, 0:18]

In [ ]:
X_train, y_train = data.get_training_data(n_hit_in=time_steps, n_hit_out=1,
                                 n_features=num_features, normalise=True)
#dataset = dataset.iloc[0:2640,0:]/   b
#dataset = dataset.iloc[0:31600,0:]
print(X_train.shape)
print(y_train.shape)
X_train.head(12)

In [ ]:
y_train.head(12)

In [ ]:
# save numpy array as npy file
from numpy import asarray
from numpy import save
from numpy import load

import os

def save_scale_param(path):
    #return data.x_scaler.mean_,  data.x_scaler.var_, data.y_scaler.mean_, data.y_scaler.var_
    save(os.path.join(path, 'x_scaler_scale.npy'), asarray(data.x_scaler.scale_))
    save(os.path.join(path, 'x_scaler_mean.npy'), asarray(data.x_scaler.mean_))
    save(os.path.join(path, 'x_scaler_var.npy'), asarray(data.x_scaler.var_))
    
    save(os.path.join(path, 'y_scaler_scale.npy'), asarray(data.y_scaler.scale_))    
    save(os.path.join(path, 'y_scaler_mean.npy'), asarray(data.y_scaler.mean_))
    save(os.path.join(path, 'y_scaler_var.npy'), asarray(data.y_scaler.var_))

def load_scale_param(path):
    x_scaler = StandardScaler()
    y_scaler = StandardScaler()

    x_scale = load(path + '/x_scaler_scale.npy')    
    x_mean = load(path + '/x_scaler_mean.npy')
    x_var = load(path + '/x_scaler_var.npy')
    
    y_scale = load(path + '/y_scaler_scale.npy')
    y_mean = load(path + '/y_scaler_mean.npy')
    y_var = load(path + '/y_scaler_var.npy')
    
    x_scaler.scale_ = x_scale
    x_scaler.mean_ = x_mean
    x_scaler.var_ = x_var
    
    y_scaler.scale_ = y_scale
    y_scaler.mean_ = y_mean
    y_scaler.var_ = y_var
    
    return x_scaler, y_scaler
    

#save_scale_param(output_path)
print('--- parameters saved ---')

In [ ]:
print(data.x_scaler.scale_)
print('----X----')
print(data.x_scaler.mean_)
print(data.x_scaler.var_)
print('----Y----')
print(data.y_scaler.mean_)
print(data.y_scaler.var_)

In [ ]:
# there is empty data?
#print(X_train.isnull().values.any())
#print(X_test.isnull().values.any())
#print(split)


In [ ]:
#X_train = data.reshape3d(X_train, time_steps, num_features)

#print('[Data] shape X_train ', X_train.shape)
#print('[Data] shape y_train ', y_train.shape)


In [ ]:
def manage_models(config):
    
    type_model = config['model']['name']
    model = None

    if type_model == 'lstm': #simple LSTM
        model = ModelLSTM(config)
    elif type_model == 'lstm-paralel':
        model = ModelLSTMParalel(config)
    elif type_model == 'cnn':
        model = ModelCNN(config)
    elif type_model == 'mlp':
        model = ModelMLP(config)        

    return model


## Create Model ##

In [ ]:
# geramos o modelo
#configs = json.load(open('config_test.json', 'r'))
model = manage_models(configs)

if model is None:
    print('Please instance model')

loadModel = configs['training']['load_model']
#loadModel = True

## Create Model ##

In [ ]:
from core.utils.metrics import *

# in-memory training
if loadModel == False:
    model.build_model()
    # in-memory training
    history = model.train(
        x=X_train,
        y=y_train,
        epochs = configs['training']['epochs'],
        batch_size = configs['training']['batch_size']
    )

    evaluate_training(history, output_path)

elif loadModel == True:       
    if not model.load_model():
        print ('[Error] please change the config file : load_model')

## Evaluate The model (just training)##

In [ ]:
#evaluate the model
from core.utils.metrics import *
#evaluate_training(history,output_path)


## Normal Prediction and Nearest ##
We concatenate features to predict one hit.

In [ ]:
# Prediction
import numpy as np
from core.utils.metrics import *
from core.utils.utils import *

In [ ]:
# not normalized 
x_scaler, y_scaler = load_scale_param(output_path)

X_test, y_test = data.get_testing_data(n_hit_in=time_steps, n_hit_out=1,
                                       n_features=num_features, normalise=False,
                                       xscaler=x_scaler, yscaler=y_scaler)

#X_test, y_test = data.get_testing_data(n_hit_in=time_steps, n_hit_out=1,
#                                       n_features=num_features, normalise=False,
#                                       xscaler=None, yscaler=None)


#X_test = X_test.iloc[0:1000,]
#y_test = y_test[0:1000]

#orig
#data.data_test.head(12)


In [ ]:
print(X_test.shape)
print(y_test.shape)
X_test.head(6)


In [ ]:
#X_test_inv = pd.DataFrame(data.inverse_transform_x(X_test))
#X_test_inv.head(12)


In [ ]:
y_test.head()


In [ ]:
# se tivese scaled
mat = convert_matrix_to_vec(y_test, 3)
scal = data.y_scaler.transform(mat)
inv = data.inverse_transform_y(scal)
inv

In [ ]:
print('----X----')
print(data.x_scaler.mean_)
print(data.x_scaler.var_)
print('----Y----')
print(data.y_scaler.mean_)
print(data.y_scaler.var_)

'''
----X----
[1.64998197e+02 2.46674255e+00 4.51951273e-01 2.41932911e+02
 3.31336219e+00 6.24867173e-01 3.38953707e+02 4.11956379e+00
 8.44515198e-01 4.55410774e+02 4.76795818e+00 1.08611730e+00]
[12336.17859739  1767.83604707   845.07801004 21304.99449295
  3074.0853378   1667.91653131 34956.50034433  4889.29844894
  3098.07273178 50047.92179565  7236.85455707  5303.03409087]
----Y----
[595.87921191   5.05573262   1.38532283]
[67778.4996686  10586.88738176  8709.42857666]

X =data.scale_data(data.data_test.values, 
                mean=[595.87921191, 5.05573262, 1.38532283],
                stds=[67778.4996686, 10586.88738176, 8709.42857666])

'''

### Normal Prediction ###

In [ ]:
x = X_test_[0]
print(x)
#x = convert_matrix_to_vec(x, 3)
x = pd.DataFrame(x)
x = data.inverse_transform_x(x.values.flatten())
print(x)
x = data.x_scaler.transform(np.reshape(x,(1,12)))
x

In [ ]:
X_test_ = data.reshape3d(X_test_inv, time_steps, num_features)
X_test_[0]

### Normal Prediction ###

In [ ]:
X_test_ = data.reshape3d(X_test, time_steps, num_features)
y_test_ = data.reshape3d(y_test, 6, num_features)

print(X_test_.shape)
print(y_test_.shape)
print(X_test_[0])
print(y_test_[1])

In [ ]:
def predict_full_sequences(x_test, data, num_hits=6, normalise=False):
    '''
        x_test: input data
        normalise: say input data must be scaled 
    '''
    timer = Timer()
    timer.start() 
    print('[Model] Predicting Sequences Started')

    total = len(x_test)

    correct = 0
    incorrect = 0
    pred_sequences = []

    for j in range(total):       
        curr_frame = x_test[j]
        predicted = []
        for i in range(num_hits):
            if normalise:
                curr_frame = data.x_scaler.transform(np.reshape(curr_frame,(1,12)))
                curr_frame_orig = data.inverse_transform_x(pd.DataFrame(curr_frame).values.flatten())
                curr_frame_orig = np.reshape(curr_frame_orig, (4,3))
                curr_frame = np.reshape(curr_frame, (4,3))
            else:
                curr_frame = curr_frame
                curr_frame_orig = curr_frame
                            
            pred = model.model.predict(curr_frame[np.newaxis,:,:])                         
            
            pred = np.reshape(pred, (1, 3))
            if normalise:
                pred = data.inverse_transform_y(pred)
            else:
                pred = pred
                
            pred = np.reshape(pred, (1, 3))
            
            predicted.append(pred)
            curr_frame = curr_frame_orig[1:]
            # inserta um  valor np.insert(array, index, value, axes)
            curr_frame = np.insert(curr_frame, [3], predicted[-1], axis=0)
            #print(curr_frame, predicted[-1])

        pred_sequences.append(predicted)

    print('[Model] Prediction Finished.')
    timer.stop()

    return pred_sequences

In [ ]:
# normalise = True say the input must be normalised
pred_full = predict_full_sequences(X_test_, data, num_hits=6, normalise=True)
print('finished prediction ...')

predicted = convert_vector_to_matrix(pred_full, 3, 6)
predicted = to_frame(predicted)
predicted.head()

In [ ]:
# original data y_true
y_test.head()

### Adding Nearest ###

In [ ]:
#bag_of_hits = None
from enum import Enum

def predict_full_sequences_nearest1(x_test, y_test, num_hits=6, num_features=3, normalise=False):
    
    timer = Timer()
    timer.start()       

    print('[Model] Predicting Sequences with Nearest Started')

    total = len(x_test)

    pred_sequences = []

    decimals = 2
    y_true = None
    
    #if normalise:
    # covert to original values
    y_true = data.inverse_transform_test_y(y_test)
        
    #y_true = y_true.round(decimals)
    
    #x_test must be in scaled form

    global bag_of_hits 
    bag_of_hits = np.array(convert_matrix_to_vec(y_true, num_features))

    y_true = np.array(y_true)
    count_correct = np.zeros(num_hits)

    for j in range(total):
        curr_frame = x_test[j]
        curr_track = y_true[j]
        
        predicted = []
        begin = 0
        #print('track :', curr_track)
        for i in range(num_hits):
            end = begin+num_features
            curr_hit_orig = curr_track[begin:end]
            begin = end
            
            #print('curr_frame:\n', curr_frame)
            # input must be scaled curr_frame
            y_pred = model.model.predict(curr_frame[np.newaxis,:,:])

            #print('pred:', y_pred)
            y_pred = np.reshape(y_pred, (1, 3))
            y_pred_orig = data.inverse_transform_y(y_pred)
            #y_pred_orig = np.round(y_pred_orig, decimals)
            #print('pred:', y_pred)
            
            print('BoH: %s, %s'%(len(bag_of_hits), bag_of_hits))

            near_pred_orig, idx = model.nearest_hit(y_pred_orig, bag_of_hits, silent=True)
            
            #print('inv pred:', y_pred_orig)
            #print('nearest:', near_pred_orig)
            #print('current:', curr_hit_orig)

            d1 = calculate_distances_vec(curr_hit_orig, y_pred_orig[0])
            d2 = calculate_distances_vec(curr_hit_orig, near_pred_orig)
            
            #print('dist pred: %s  dist near : %s ' % (d1, d2))
            
            #bag_of_hits = np.delete(bag_of_hits, idx, 0)
            
            #if np.logical_and(curr_hit, near_pred).all():
            #if np.array_equal(curr_hit, near_pred):
                          
            if d1 <= d2:
                # original coordinates
                if np.isclose(curr_hit_orig, y_pred_orig, atol=0.09).all():    
                    count_correct[i]=+1
                    
                predicted.append(y_pred)
            else:
                # original coordinates
                if np.isclose(curr_hit_orig, near_pred_orig, atol=0.09).all():    
                    count_correct[i]=+1
                               
                near_pred = data.y_scaler.transform(np.reshape(near_pred_orig, (1, 3)))
                #print('current inv:', near_pred)
                predicted.append(near_pred)
                      
            curr_frame = curr_frame[1:]
            # inserta um  valor np.insert(array, index, value, axes)
            curr_frame = np.insert(curr_frame, [3], predicted[-1], axis=0)
        
        pred_sequences.append(predicted)
        if j == 2: break
    print('[Model] Prediction Finished.')
    timer.stop()

    return pred_sequences, count_correct

def nearest_hit(hit, hits,
                    silent = True,
                    metric = 'euclidean'):

    if silent is False:
        timer = Timer()
        timer.start()

    dist = distance.cdist(hits, hit, metric)

    # get the index of minimum distance
    target_hit_index = np.argmin(dist)

    if silent is False:    
        print("--- N_hits: %s" % len(hits))
        print("--- Hit index: %s" % target_hit_index)
        print("--- " + str(metric) + " distance: " + str(dist[target_hit_index]))
        print("--- time: %s seconds" % timer.stop())

    # get hits coordinates 
    real_hit = hits[target_hit_index, :]
    real_hit = np.array(real_hit)

    # removing the hit from bag
    #hits = np.delete(hits, target_hit_index, 0)

    if dist_hit is False:
        return real_hit, target_hit_index
    else:
        return real_hit, target_hit_index, np.min(dist)

def mat_rhoetaphi_to_xyz(mat, n_hits = 5):
    pivot_tmp = 0
    for i in range(n_hits):
        pivot_tmp = i * 3
        rho = mat[pivot_tmp + 0]
        eta = mat[pivot_tmp + 1]
        phi = mat[pivot_tmp + 2]
        if (rho != 0 and eta != 0 and phi != 0):
            x, y, z = convert_rhoetaphi_to_xyz(rho, eta, phi)
            mat[pivot_tmp + 0] = x
            mat[pivot_tmp + 1] = y
            mat[pivot_tmp + 2] = z
    return mat

class BagOfHits(Enum):
    All=1,
    Track=2,
    Layer=3
    
def predict_full_sequences_nearest2(x_test, y_test, bag_of_hits, y_test_aux=None, num_hits=6, num_features=3,
                                    normalise=False, cylindrical=False, verbose=False, tol=0.01):
    
    '''
        This function shift the window by 1 new prediction each time, re-run predictions on new window
        parameters:
        x_test : X test data normaly not scaled (4 hits)
        y_test : y test data, normaly not scaled (6 hits)
        num_hits : how many hits by y_test
        normalise : it param says the input data must be scaled or not
    
    '''
    
    timer = Timer()
    timer.start()

    print('[Model] Predicting Sequences with Nearest Started')

    total = len(x_test)

    pred_sequences = []
    pred_sequences_orig = []
    
    decimals = 2
   
    # covert to original values
    #y_true = data.inverse_transform_test_y(y_test)
    #y_true = y_true.round(decimals)
    
    #change the dataset by cartesian coordinates
    if cylindrical:
        y_test = y_test_aux
    else:
        y_test = y_test
        
    # bag_of_hits  
    bag_of_hits_all = np.array(convert_matrix_to_vec(y_test, num_features))

    count_correct = np.zeros(num_hits)
    begin_idx, end_idx = 0, 0
    num_boh = 6
    
    for j in range(total):
        curr_frame = x_test[j]
        # bag_of_hit by track
        curr_track = np.array(y_test.iloc[j,0:]).reshape(num_hits, num_features)
        
        if verbose:
            print('curr_track %s , %s:' % (j , curr_track))

        predicted = []
        predicted_orig = []
        begin = 0
        for i in range(num_hits):
            # bag_of_hit by layer
            end = begin+num_features
            curr_layer = np.array(y_test.iloc[0:,begin:end]).reshape(total, num_features)
            curr_hit = curr_track[i]
            begin = end
            
            if verbose:
                # primeira esta em originais
                print('input:\n', curr_frame)
            
            if normalise:
                curr_frame = data.x_scaler.transform(np.reshape(curr_frame,(1,12)))
                curr_frame_orig = data.inverse_transform_x(pd.DataFrame(curr_frame).values.flatten())
                curr_frame_orig = np.reshape(curr_frame_orig, (4,3))
                curr_frame = np.reshape(curr_frame, (4,3))
            else:
                curr_frame = curr_frame
                curr_frame_orig = curr_frame
                
            if verbose:
                print('input:\n', curr_frame)
                #print('input orig:\n', curr_frame_orig)
            
            #print('input inv :\n', curr_frame_inv.reshape(4,3))
            #print('newaxis ', curr_frame[np.newaxis,:,:])
            # input must be scaled curr_frame
            y_pred = model.model.predict(curr_frame[np.newaxis,:,:])

            
            y_pred = np.reshape(y_pred, (1, 3))
            if normalise:
                y_pred_orig = data.inverse_transform_y(y_pred)
            else:
                y_pred_orig = y_pred

            y_pred_orig = np.reshape(y_pred_orig, (1, 3))

            if bag_of_hits == BagOfHits.All:
                hits = bag_of_hits_all
            elif bag_of_hits == BagOfHits.Track:
                hits = curr_track
            elif bag_of_hits == BagOfHits.Layer:                    
                hits = curr_layer
            
            if cylindrical:
                rho, eta, phi = y_pred_orig[0][0], y_pred_orig[0][1], y_pred_orig[0][2]
                #print(rho,eta,phi)
                x, y, z = convert_rhoetaphi_to_xyz(rho, eta, phi)
                #print(x,y,z)
                y_pred_orig[0][0] = x
                y_pred_orig[0][1] = y
                y_pred_orig[0][2] = z
                
                #print(y_pred_orig)
                    
            dist = distance.cdist(hits, y_pred_orig, 'euclidean')
            idx = np.argmin(dist)
            near_pred = hits[idx]

            # if curr_hit is in cartesian coord, near_pred must be in cartesian coord too
            if np.isclose(curr_hit, near_pred, atol=tol).all():
                count_correct[i]+=1
                #print('count_correct[%s] = %s ' % (i, count_correct[i]))
                
            if verbose:
                print('pred:', y_pred)
                print('inv pred:', y_pred_orig)
                print('current:', curr_hit)
                print('nearest:', near_pred)
            
            if cylindrical:
                x, y, z = near_pred[0], near_pred[1], near_pred[2]
                #print(x,y,z)
                rho, eta, phi = convert_xyz_to_rhoetaphi(x, y, z)
                #print(rho,eta,phi)
                near_pred[0] = rho
                near_pred[1] = eta
                near_pred[2] = phi
                
            #curr_track = np.delete(curr_track, idx, 0)
            #near_pred_orig, idx = model.nearest_hit(y_pred_orig, bag_of_hits, silent=True)
            
           
            
            '''            
            d1 = calculate_distances_vec(curr_hit, y_pred_orig[0])
            d2 = calculate_distances_vec(curr_hit, near_pred)
            #print('d1 %s, d2 %s' % (d1, d2))
            
            if d1 <= d2:
                # original coordinates
                if np.isclose(curr_hit, y_pred_orig, atol=0.09).all():    
                    count_correct[i]=+1
                #print('d1')    
                predicted.append(y_pred)
                predicted_orig.append(y_pred_orig)
            else:
                # original coordinates
                if np.isclose(curr_hit, near_pred_orig, atol=0.09).all():    
                    count_correct[i]=+1
                #print('d2')                                         
                near_pred_scaled = data.y_scaler.transform(np.reshape(near_pred, (1, 3)))
                print('near scaled:', near_pred_scaled)
                predicted.append(near_pred_scaled)
                predicted_orig.append(near_pred)
            '''
            
            '''
            near_pred = np.reshape(near_pred, (1, 3))
            if normalise:
                near_pred = data.y_scaler.transform(near_pred)
            else:
                near_pred = near_pred
            
            if verbose:
                print('near scaled:', near_pred)
            '''   
            
 
                    
            #near adiciona em valores originaeis
            predicted.append(near_pred)
            
            #predicted_orig.append(near_pred_orig)
            #print('-----\n')
            
            curr_frame = curr_frame_orig[1:]
            curr_frame = np.insert(curr_frame, [3], predicted[-1], axis=0)
            
            #curr_frame_new = data.x_scaler.transform(np.reshape(curr_frame_inv, (1, 12)))
            #curr_frame_new_inv = data.inverse_transform_x(pd.DataFrame(curr_frame).values.flatten())
            
            #print('new frame ', curr_frame_new.reshape(4,3))
            #print('new frame inv ', curr_frame_new_inv.reshape(4,3))
            
        pred_sequences.append(predicted)
        #pred_sequences_orig.append(predicted_orig)
        
        if verbose:
            if j == 3: break
                
    print('[Model] Prediction Finished.')
    timer.stop()

    return pred_sequences, count_correct

In [ ]:
#X_test = X_test.iloc[0:1000,]
#y_test = y_test[0:1000]
X_test_ = data.reshape3d(X_test, time_steps, num_features)
y_test_ = data.reshape3d(y_test, 6, num_features)

print(X_test_.shape)
print(y_test_.shape)

In [ ]:
#pred_full_res, correct = predict_full_sequences_nearest1(X_test_, y_test, 6)
#print('finished prediction nearest...')

#predicted_nearest = convert_vector_to_matrix(pred_full_res, 3, 6)
#predicted_nearest = to_frame(predicted_nearest)
#predicted_nearest.head()


In [ ]:
# aux data
data_tmp = Dataset(path, split_data, False, num_hits, KindNormalization.Zscore)
X_test_aux, y_test_aux = data_tmp.get_testing_data(n_hit_in=time_steps, n_hit_out=1,
                                 n_features=num_features, normalise=False)


In [ ]:
X_test_aux = X_test_aux.iloc[0:1000,]
y_test_aux = y_test_aux[0:1000]
X_test_aux.head()

In [ ]:

# normalise = True say input data must be scaled or not 
pred_full_res, correct = predict_full_sequences_nearest2(X_test_, y_test, BagOfHits.Layer, None, 6, 
                                                         normalise=True, cylindrical=False,
                                                         verbose=False, tol=0.01)

predicted_nearest = convert_vector_to_matrix(pred_full_res, 3, 6)
predicted_nearest = to_frame(predicted_nearest)
predicted_nearest.head()


In [ ]:
# vetor de contagens
total = X_test.shape[0]
print(correct)
#taxa_acertos = [(correct*100)/total for x in range(0, len(correct))]
print((correct*100)/total)

In [ ]:
from matplotlib import pyplot as plt
#plt.bar(range(1,6), correct)
layers = ['layer 5', 'layer 6','layer 7','layer 8','layer 9','layer 10']

#plt.bar(np.arange(1, 6, 1), correct)
plt.bar(layers, correct)

In [ ]:
y_test.head()

In [ ]:
curr_track 0 , [[220.0039978  143.64300537  13.80000019]
 [309.77398682 192.727005    22.20000076]
 [433.60699463 252.54699707  35.40000153]
 [586.02099609 313.86199951  49.79999924]
 [735.70300293 362.45001221  65.19999695]
 [935.93103027 410.11999512  86.80000305]]:
input:    
[[ 25.9116993   18.92830086  -6.89595985]
 [ 59.46440125  42.51089859  -3.20423007]
 [ 94.53399658  66.21589661   0.57812101]
 [142.01199341  96.84390259   5.62239981]]    

curr_track 1 :    
[[ 257.53500366   17.9375      128.80000305]
 [ 361.7749939    29.22640038  182.19999695]
 [ 497.4670105    47.53120041  251.80000305]
 [ 656.45397949   73.98660278  333.6000061 ]
 [ 814.44396973  105.75900269  417.3999939 ]
 [1007.89001465  152.21299744  520.40002441]]:  
input:
 [[ 31.56760025   1.38691998  13.81000042]
 [ 72.24410248   3.5746901   34.45349884]
 [115.68099976   6.29080009  56.51910019]
 [171.48800659  10.3526001   84.90619659]]

In [ ]:

y_test_inv = data.inverse_transform_test_y(y_test)
y_test_inv = pd.DataFrame(y_test_inv)


boh_layer = np.array(y_test_inv.iloc[0:,0:3]).reshape(len(y_test_inv),3)
boh_track = np.array(y_test_inv.iloc[0,0:]).reshape(6,3)
boh_all = np.array(convert_matrix_to_vec(y_test_inv, 3))
print(boh_track[1])


#current = [[ 331.34717,  -142.58179,    -6.709302]] 
pred = [[ 235.75716,  -109.62279,    -3.109302]]
n = model.nearest_hit(pred, boh_all, silent=False)
n


#inv pred: [[ 235.75716  -109.62279    -3.109302]]
#nearest: [ 236.97200012 -107.73600006   -3.        ]
#current: [ 236.97200012 -107.73600006   -3.        ]

In [ ]:
y = data.inverse_transform_test_y(y_test)
#y = np.array(y)
#y = pd.DataFrame(y)
#y

#track = pd.DataFrame(y[0])
#t = np.reshape(track, 1, 18)
#t
#np.array(track)

boh = np.array(convert_matrix_to_vec(y, num_features))
#boh[0:6]
boh

#boh = convert_matrix_to_vec(track, num_features)
#
#boh
#print(y_test.shape)
#print(len(boh))



In [ ]:

'''
current_track = np.array([[236.97, -107.74, -3.],
                 [332.56, -140.7, -6.6],
                 [468.9,  -177.86,  -10.2],
                 [630.02, -208.33,  -15.],
                 [791.81, -224.49,  -16.2],
                 [997.68,-224.02,  -27.]])
'''

tracks = np.array([
 [ 332.56201172, -140.69500732,   -6.5999999 ],
 [ 468.89599609, -177.86099243,  -10.19999981],
 [ 630.02398682, -208.33099365,  -15.        ],
 [ 791.80603027, -224.48699951,  -16.20000076],
 [ 997.67901611, -224.02400208,  -27.        ]])

current = [[236.97200012, -107.73600006, -3. ]]
pred = [[239.28717, -102.406906, -5.2484846]]
pred = [[ 245.10965, -117.84069,   -6.3022523]]
n = model.nearest_hit(pred, tracks, silent=False)
n

In [ ]:
near = np.array([[332.56, -140.7, -6.6 ]])
scaled = data.y_scaler.transform(near)
print(scaled)
orig = data.inverse_transform_y(scaled)
print(orig)

In [ ]:
 [[-1.22701239e+00  4.67683517e-01 -4.26419735e-02]
 [-1.28115966e+00  5.49873417e-01 -1.11877660e-04]
 [-1.37037903e+00  6.30455206e-01  3.19417376e-02]
 [-1.40640257e+00  7.44980250e-01  6.58394857e-02]]

In [ ]:
# convertimos a matriz do test em um vetor 
#y_test_ = convert_matrix_to_vec(y_test, 3)
#y_test_ = np.array(y_test_)

pred_full_res, correct = model.predict_full_sequences_nearest(X_test_, y_test, 6)
print('finished prediction nearest...')

predicted_nearest = convert_vector_to_matrix(pred_full_res, 3, 6)
predicted_nearest = to_frame(predicted_nearest)
predicted_nearest.head()


In [ ]:
def calc_score1(y_true, y_predicted, report=False):

    r2 = r2_score(y_true, y_predicted)
    mse = mean_squared_error(y_true, y_predicted)
    rmse = sqrt(mean_squared_error(y_true, y_predicted))
    mae = mean_absolute_error(y_true, y_predicted)
    
    report_string = ""
    report_string += "---Regression Scores--- \n"
    report_string += "\tR_2 statistics        (R2)  = " + str(round(r2,3)) + "\n"
    report_string += "\tMean Square Error     (MSE) = " + str(round(mse,3)) + "\n"
    report_string += "\tRoot Mean Square Error(RMSE) = " + str(round(rmse,3)) + "\n"
    report_string += "\tMean Absolute Error   (MAE) = " + str(round(mae,3)) + "\n"

    if report:
        return r2, mse, rmse, mae, report_string
    else:
        return r2, mse, rmse, mae

def calc_score_layer(y_true, y_pred, n_features):
    rows = y_true.shape[0]
    cols = y_true.shape[1]
    begin, end = 0, 0
    layer = 5
    for i in range(0, cols, n_features):
        end = i + n_features
        layer_true = y_true.iloc[0:,begin:end]
        layer_pred = y_pred.iloc[0:,begin:end]
        begin = end
        
        r2, mse, rmse, mae, result = calc_score1(data.reshape2d(layer_true, 1),
                            data.reshape2d(layer_pred, 1), report=True)   
        
        print('layer ', layer)
        print(result)
        layer+=1

def calc_score_layer_axes(y_true, y_predicted, features=3):
    '''
        Return 
            receive a sequence by track and calculate the score by layer
            score  : return the score total with RMSE
            scores : return the score RMSE for each features
    '''
    mses = []
    rmses = []
    r2s = []
    
    y_true = np.array(y_true)
    y_predicted = np.array(y_predicted)
    
    rows = y_true.shape[0]
    cols = y_true.shape[1]

    mse_x, mse_y, mse_z = 0,0,0
    r2_x, r2_y, r2_z = 0,0,0
    counter = 0
    for j in range(0, cols, features):
        x, y, z = (j + 0),  (j + 1), (j + 2)
        # calculate by column
        mse_x+= mean_squared_error(y_true[:,x], y_predicted[:,x])
        mse_y+= mean_squared_error(y_true[:,y], y_predicted[:,y])
        mse_z+= mean_squared_error(y_true[:,z], y_predicted[:,z])

        # adding mse by layer
        mses.append([mse_x, mse_y, mse_z])
        rmses.append([sqrt(mse_x), sqrt(mse_y), sqrt(mse_z)])
        
        r2_x+= r2_score(y_true[:,x], y_predicted[:,x])
        r2_y+= r2_score(y_true[:,y], y_predicted[:,y])
        r2_z+= r2_score(y_true[:,z], y_predicted[:,z])
        r2s.append([r2_x, r2_y, r2_z])
        
        counter+=1
        #mse = mean_squared_error(y_true[:,i], y_predicted[:,i])
        
        #mse = mean_squared_error(y_true[i,j:end_idx], y_predicted[i,j:end_idx])      
        #r2 = r2_score(y_true[:,i], y_predicted[:,i])
        #r2 = r2_score(y_true[i,j:end_idx], y_predicted[i,j:end_idx])        

    #rmses.append(sqrt(mse_x/(rows)))  
    #rmses.append(sqrt(mse_y/(rows)))
    #rmses.append(sqrt(mse_z/(rows))) 
    
    #print(r2_x, r2_y, r2_z)
    #r2s.append(r2_x/(rows))
    #r2s.append(r2_y/(rows))
    #r2s.append(r2_z/(rows))
        
 

    return mses, rmses, r2s

def summarize_scores_axes(mses, rmses, r2s):
    
    counter = 0
    for mse, rmse in zip(mses,rmses):
        print('layer %s' % counter)
        print('\tMSE:[%.2f, %.2f, %.2f]' % (mse[0], mse[1], mse[2]))
        print('\tRMSE:[%.2f, %.2f, %.2f]' % (rmse[0], rmse[1], rmse[2]))
        counter+=1

### Metrics for Normal Prediction ###

In [ ]:
# metricas geraeis
_,_,_,_,result = calc_score1(data.reshape2d(y_test, 1),
                    data.reshape2d(predicted, 1), report=True)
print(result)

calc_score_layer(y_test, predicted, n_features=3)

mses, rmses, r2s = calc_score_layer_axes(y_test, predicted)
summarize_scores_axes(mses, rmses, r2s)


### Metrics for  Nearest Prediction ###

In [ ]:
# metricas para nearest
_,_,_,_,result = calc_score1(data.reshape2d(y_test, 1),
                    data.reshape2d(predicted_nearest, 1), report=True)
print(result)

calc_score_layer(y_test, predicted_nearest, n_features=3)

mses, rmses, r2s = calc_score_layer_axes(y_test, predicted_nearest)
summarize_scores_axes(mses, rmses, r2s)

### Convert to Millimeters ###

In [ ]:
def inverse_transform_mat(scaler, data, n_features=3):
    '''
        Covert a matrix to scaled values by colum hit 
    '''
    rows = data.shape[0]
    cols = data.shape[1]
    
    begin = 0
    for i in range(0, cols, n_features):
        end = i + n_features
        hit_col = data.iloc[0:,begin:end]
        begin = end
        scaled = scaler.transform(hit_col)
        print(scaled)

inverse_transform_mat(data.y_scaler, predicted_nearest)

In [ ]:
normalise = False     
if normalise:
    print('[Data] Inverse Transforming ...')
    y_test_orig = data.inverse_transform_test_y(y_test)
    y_predicted_orig = data.inverse_transform_test_y(predicted)
    y_predicted_orig_nearest = data.inverse_transform_y(predicted_nearest)
    
    y_test_orig = pd.DataFrame(y_test_orig)    
    y_predicted_orig = pd.DataFrame(y_predicted_orig)    
else:
    y_test_orig = y_test
    y_predicted_orig = predicted
    
    y_predicted_orig_nearest = predicted_nearest
    y_predicted_orig_nearest = pd.DataFrame(y_predicted_orig_nearest)

print('[Data] shape y_predicted_orig ', y_predicted_orig.shape)    
print('[Data] shape y_test_orig ', y_test_orig.shape)

result = calc_score(data.reshape2d(y_test_orig, 1),
                    data.reshape2d(y_predicted_orig_nearest, 1), report=False)
print(result)
r2, rmse, rmses = evaluate_forecast_seq(y_test_orig, y_predicted_orig_nearest)
summarize_scores(r2, rmse, rmses)


## Prepare data for Visualization ##

In [ ]:
x_true, y_true = data.get_testing_data(n_hit_in=time_steps, n_hit_out=1,
                                 n_features=num_features, normalise=False)
x_true = x_true.iloc[0:1000,]
y_true = y_true[0:1000]

#x_true = X_test
#y_true = y_test
print(x_true.shape)
print(y_true.shape)

In [ ]:
# join both dataset must be equal to X_test
data_true = np.concatenate([x_true , y_true], axis = 1)
data_true = pd.DataFrame(data_true)
data_true.columns.name = 'real' 

print('Shape ', data_true.shape)

In [ ]:
# must be equal
#data_test.values == X_test_new.values


In [ ]:
# join both dataset should be equal to X_test but not equal
data_pred = np.concatenate([x_true , y_predicted_orig], axis = 1 )
data_pred = pd.DataFrame(data_pred)
data_pred.columns.name = 'predito'

print('Shape ', data_pred.shape)

In [ ]:
# join both dataset should be equal to X_test but not equal
data_pred_nearest = np.concatenate([x_true , y_predicted_orig_nearest], axis = 1 )
data_pred_nearest = pd.DataFrame(data_pred_nearest)

data_pred_nearest.columns.name = 'nearest'

print('Shape ', data_pred_nearest.shape)

In [ ]:
# should not be equal
#data_pred.values == X_test_new.values

In [ ]:
if cylindrical:

    y_test_orig.to_csv(os.path.join(output_path, 'y_true_%s_cylin_nearest.csv' % configs['model']['name']),
                header=False, index=False)

    y_predicted_orig.to_csv(os.path.join(output_path, 'y_pred_%s_cylin_nearest.csv' % configs['model']['name']),
                header=False, index=False)

    x_true.to_csv(os.path.join(output_path, 'x_true_%s_cylin_nearest.csv' % configs['model']['name']),
                header=False, index=False)
else:
    
    y_test_orig.to_csv(os.path.join(output_path, 'y_true_%s_xyz_nearest.csv' % configs['model']['name']),
                header=False, index=False)
    y_predicted_orig.to_csv(os.path.join(output_path, 'y_pred_%s_xyz_nearest.csv' % configs['model']['name']),
                header=False, index=False)

    x_true.to_csv(os.path.join(output_path, 'x_true_%s_xyz_nearest.csv' % configs['model']['name']),
                header=False, index=False)

print('[Output] Results saved at %', output_path)

## Visualization ##

In [ ]:
# Dados originais
N_tracks = 50
path_html = ''
name = configs['model']['name']

if cylindrical:
    path_html=os.path.join(output_path, 'track-original-%s_cylin_nearest.html' % name)
else:
    path_html=os.path.join(output_path, 'track-original-%s_xyz_nearest.html' % name)
    
fig = track_plot_xyz([data_true], n_hits = 10, cylindrical = cylindrical, n_tracks = 50, 
               path=path_html, title='Track Original #10 Hit - Model %s' % name.upper())

fig.show()

In [ ]:
# predicted data
N_tracks = 8
path_html = ''
name = configs['model']['name']

if cylindrical:
    path_html=os.path.join(output_path, 'track-predicted-%s_cylin_normal-pred.html' % name)
else:
    path_html=os.path.join(output_path, 'track-predicted-%s_xyz_normal-pred.html' % name)
    
fig = track_plot_xyz([data_true, data_pred], n_hits = 10, cylindrical = cylindrical, n_tracks = N_tracks, 
               path=path_html, title='Track Prediction #10 Hit - Model %s (Nearest hits)' % name.upper(), auto_open=True)

fig.show()

In [ ]:
# predicted data
N_tracks = 8
path_html = ''
name = configs['model']['name']

if cylindrical:
    path_html=os.path.join(output_path, 'track-predicted-%s_cylin_nearest.html' % name)
else:
    path_html=os.path.join(output_path, 'track-predicted-%s_xyz_nearest.html' % name)


fig = track_plot_xyz([data_true, data_pred_nearest], n_hits = 10, cylindrical = cylindrical, n_tracks = N_tracks, 
               path=path_html, title='Track Prediction #10 Hit - Model %s (Nearest hits)' % name.upper(), auto_open=True)

fig.show()

In [ ]:
# predicted data
N_tracks = 8
path_html = ''
name = configs['model']['name']

if cylindrical:
    path_html=os.path.join(output_path, 'track-predicted-%s_cylin_nearest.html' % name)
else:
    path_html=os.path.join(output_path, 'track-predicted-%s_xyz_nearest.html' % name)


fig = track_plot_xyz([data_true, data_pred, data_pred_nearest], n_hits = 10, cylindrical = cylindrical, n_tracks = N_tracks, 
               path=path_html, title='Track Prediction #10 Hit - Model %s (Nearest hits)' % name.upper(), auto_open=True)

fig.show()